// Package ddev drives the local DDEV project of a site.
package ddev

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/usermind/wpsync/internal/agentapi"
)

// Runner executes ddev commands in a site directory.
type Runner interface {
	Run(args ...string) error
	Output(args ...string) (string, error)
	RunStdin(stdin io.Reader, args ...string) error
}

// Exec runs the real ddev binary.
type Exec struct {
	Dir    string
	Stdout io.Writer
	Stderr io.Writer
}

func (e *Exec) cmd(args ...string) *exec.Cmd {
	c := exec.Command("ddev", args...)
	c.Dir = e.Dir
	c.Stdout = e.Stdout
	c.Stderr = e.Stderr
	return c
}

// Run runs ddev with output to Stdout/Stderr.
func (e *Exec) Run(args ...string) error {
	if err := e.cmd(args...).Run(); err != nil {
		return fmt.Errorf("ddev %s: %w", strings.Join(args, " "), err)
	}
	return nil
}

// Output runs ddev and returns stdout.
func (e *Exec) Output(args ...string) (string, error) {
	c := e.cmd(args...)
	c.Stdout = nil
	out, err := c.Output()
	if err != nil {
		return "", fmt.Errorf("ddev %s: %w", strings.Join(args, " "), err)
	}
	return string(out), nil
}

// RunStdin runs ddev with stdin, e.g. `ddev mysql` for imports.
func (e *Exec) RunStdin(stdin io.Reader, args ...string) error {
	c := e.cmd(args...)
	c.Stdin = stdin
	if err := c.Run(); err != nil {
		return fmt.Errorf("ddev %s: %w", strings.Join(args, " "), err)
	}
	return nil
}

// Exists reports whether siteDir already has a DDEV project.
func Exists(siteDir string) bool {
	_, err := os.Stat(filepath.Join(siteDir, ".ddev", "config.yaml"))
	return err == nil
}

// Setup creates the DDEV project on the first pull.
func Setup(r Runner, siteDir, name string, env agentapi.Env, mailguardSource string) error {
	if err := os.MkdirAll(filepath.Join(siteDir, "public"), 0o755); err != nil {
		return err
	}
	if err := r.Run("config",
		"--project-name="+name,
		"--project-type=wordpress",
		"--docroot=public",
		"--php-version="+MajorMinor(env.PHPVersion),
		"--database="+DatabaseSpec(env.DBServer),
		// OrbStack has fast bind mounts; Mutagen would sync the mailguard mount back as a copy (Spike B5).
		"--performance-mode=none",
	); err != nil {
		return err
	}
	if err := WriteMailguardMount(siteDir, mailguardSource); err != nil {
		return err
	}
	if err := r.Run("start", "-y"); err != nil {
		return err
	}
	if err := r.Run("wp", "core", "download", "--version="+env.WPVersion, "--skip-content", "--force"); err != nil {
		return err
	}
	if err := ClaimWPConfig(siteDir); err != nil {
		return err
	}
	if env.TablePrefix != "" && env.TablePrefix != "wp_" {
		return r.Run("wp", "config", "set", "table_prefix", env.TablePrefix, "--type=variable")
	}
	return nil
}

// WriteMailguardMount mounts the mailguard file read-only into the container as a mu-plugin.
// A host symlink would not resolve inside the container, hence a bind mount.
func WriteMailguardMount(siteDir, source string) error {
	if _, err := os.Stat(source); err != nil {
		return fmt.Errorf("local-mailguard source missing at %s – refusing to set up a site without mail protection", source)
	}
	compose := fmt.Sprintf(`# Generated by wpsync – mounts local-mailguard read-only as mu-plugin
services:
  web:
    volumes:
      - "%s:/var/www/html/public/wp-content/mu-plugins/00-local-mailguard.php:ro"
`, source)
	return os.WriteFile(filepath.Join(siteDir, ".ddev", "docker-compose.mailguard.yaml"), []byte(compose), 0o644)
}

const ddevMarker = "#ddev-generated"

// ClaimWPConfig removes DDEV's marker so DDEV stops regenerating wp-config.php and
// dropping prefix and constants (Spike B15, AC-20). wp-config-ddev.php stays DDEV-managed.
func ClaimWPConfig(siteDir string) error {
	p := filepath.Join(siteDir, "public", "wp-config.php")
	data, err := os.ReadFile(p)
	if err != nil {
		return fmt.Errorf("read wp-config.php: %w", err)
	}
	claimed := strings.Replace(string(data), ddevMarker, "wpsync-managed (DDEV marker removed so DDEV no longer overwrites this file)", 1)
	return os.WriteFile(p, []byte(claimed), 0o644)
}

// DatabaseSpec maps the source server version to a DDEV database spec (Spike B17, AC-19).
func DatabaseSpec(server string) string {
	version := MajorMinor(strings.SplitN(server, "-", 2)[0])
	switch {
	case strings.Contains(strings.ToLower(server), "mariadb"):
		return "mariadb:" + version
	case version == "5.7" || version == "8.0" || version == "8.4":
		return "mysql:" + version
	default:
		return "mysql:8.0"
	}
}

// MajorMinor turns "8.2.29" into "8.2".
func MajorMinor(version string) string {
	parts := strings.SplitN(version, ".", 3)
	if len(parts) < 2 {
		return version
	}
	return parts[0] + "." + parts[1]
}

// LocalURL returns the project's HTTP URL.
func LocalURL(r Runner) (string, error) {
	out, err := r.Output("describe", "-j")
	if err != nil {
		return "", err
	}
	return parseDescribe([]byte(out))
}

func parseDescribe(data []byte) (string, error) {
	var d struct {
		Raw struct {
			HTTPURL string `json:"httpurl"`
		} `json:"raw"`
	}
	if err := json.Unmarshal(data, &d); err != nil {
		return "", fmt.Errorf("parse ddev describe: %w", err)
	}
	if d.Raw.HTTPURL == "" {
		return "", errors.New("ddev describe: no httpurl")
	}
	return d.Raw.HTTPURL, nil
}
