package ddev

import (
	"fmt"
	"os"
)

// wpsync's own compose files in .ddev. Their content is fixed by wpsync and checked on every pull.
const (
	MailguardComposeFile = "docker-compose.mailguard.yaml"
	HardeningComposeFile = "docker-compose.wpsync-hardening.yaml"
)

// MailguardCompose mounts the mailguard file read-only into the web container as a mu-plugin.
// A host symlink would not resolve inside the container, hence a bind mount.
func MailguardCompose(source string) string {
	return fmt.Sprintf(`# Generated by wpsync – mounts local-mailguard read-only as mu-plugin
services:
  web:
    volumes:
      - "%s:/var/www/html/public/wp-content/mu-plugins/00-local-mailguard.php:ro"
`, source)
}

// HardeningCompose makes .ddev read-only in web and db. Site code runs in these containers; a
// writable .ddev lets it add hooks or host commands that the ddev binary then runs on the Mac.
// DDEV mounts .ddev rw into db for snapshots and writes them to /mnt/ddev_config/db_snapshots,
// so that one directory stays writable. Compose merges volumes by target, which replaces DDEV's
// own /mnt/ddev_config mount.
func HardeningCompose() string {
	return `# Generated by wpsync – .ddev is read-only in the containers (only db_snapshots stays writable)
services:
  web:
    volumes:
      - ".:/var/www/html/.ddev:ro"
  db:
    volumes:
      - ".:/mnt/ddev_config:ro"
      - "./db_snapshots:/mnt/ddev_config/db_snapshots"
`
}

// OwnFiles returns wpsync's compose files with their expected content, keyed by name in .ddev.
func OwnFiles(mailguardSource string) (map[string]string, error) {
	if _, err := os.Stat(mailguardSource); err != nil {
		return nil, fmt.Errorf("local-mailguard source missing at %s – refusing to set up a site without mail protection", mailguardSource)
	}
	return map[string]string{
		MailguardComposeFile: MailguardCompose(mailguardSource),
		HardeningComposeFile: HardeningCompose(),
	}, nil
}
