package ddev

import (
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"path/filepath"
	"strings"
	"time"

	"github.com/usermind/wpsync/internal/safefs"
)

const (
	proxyZoneFile = "wpsync-uploads-zone.conf"
	proxyFile     = "wpsync-uploads-proxy.conf"
)

// UploadsProxyConfig returns the http-level rate-limit zone and the server-level locations that
// fetch a missing upload once from the source, store it below public/ and throttle to 2 requests
// per second (AC-16, E16). DDEV copies .ddev/nginx_full/*.conf to /etc/nginx/sites-enabled/
// (http context) and includes .ddev/nginx/*.conf in the server block.
func UploadsProxyConfig(sourceURL, userAgent string) (zone, server string, err error) {
	u, err := url.Parse(sourceURL)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return "", "", fmt.Errorf("invalid source URL %q", sourceURL)
	}
	if strings.ContainsAny(sourceURL+userAgent, "\"';{}$\n\r") {
		return "", "", fmt.Errorf("refusing unsafe characters in proxy config: %q", sourceURL)
	}
	rewrite := ""
	if base := strings.TrimRight(u.Path, "/"); base != "" {
		rewrite = fmt.Sprintf("    rewrite ^ %s$wpsync_path break;\n", base)
	}
	zone = "# Generated by wpsync – throttles the uploads proxy (E16)\n" +
		"limit_req_zone $server_name zone=wpsync_uploads:1m rate=2r/s;\n"
	server = fmt.Sprintf(`# Generated by wpsync – missing uploads are fetched once from the source and stored locally (AC-16)
location ^~ /wp-content/uploads/ {
    try_files $uri @wpsync_source;
    access_log off;
}

location @wpsync_source {
    limit_req zone=wpsync_uploads burst=500;
    resolver 127.0.0.11 valid=300s ipv6=off;
    set $wpsync_path $uri;
    set $wpsync_source "%s://%s";
%s    proxy_pass $wpsync_source;
    proxy_set_header Host "%s";
    proxy_set_header User-Agent "%s uploads-proxy";
    proxy_ssl_server_name on;
    proxy_store /var/www/html/public$wpsync_path;
    proxy_store_access user:rw group:rw all:r;
    proxy_temp_path /var/www/html/.wpsync/proxy-tmp;
}
`, u.Scheme, u.Host, rewrite, u.Host, userAgent)
	return zone, server, nil
}

// WriteUploadsProxy writes or removes the proxy config; changed tells whether DDEV must restart.
func WriteUploadsProxy(siteDir, sourceURL, userAgent string, enabled bool) (bool, error) {
	zonePath := filepath.Join(siteDir, ".ddev", "nginx_full", proxyZoneFile)
	serverPath := filepath.Join(siteDir, ".ddev", "nginx", proxyFile)
	files := map[string]string{zonePath: "", serverPath: ""}
	if enabled {
		zone, server, err := UploadsProxyConfig(sourceURL, userAgent)
		if err != nil {
			return false, err
		}
		files[zonePath], files[serverPath] = zone, server
		// .wpsync/ lies in the DDEV mount: a symlink there is refused, not followed (SEC-113).
		tmp, err := safefs.OpenTree(siteDir, filepath.Join(".wpsync", "proxy-tmp"))
		if err != nil {
			return false, err
		}
		tmp.Close()
	}
	changed := false
	for path, content := range files {
		rel, err := filepath.Rel(siteDir, filepath.Dir(path))
		if err != nil {
			return false, err
		}
		// .ddev lies in the site folder: never write or delete through a symlink there (N-d).
		open := safefs.OpenTree
		if content == "" {
			open = safefs.OpenDir // removing creates no folder
		}
		root, err := open(siteDir, rel)
		if content == "" && errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return false, err
		}
		name := filepath.Base(path)
		old, err := safefs.ReadFile(root, name)
		exists := err == nil
		switch {
		case content == "" && exists:
			err = safefs.Remove(root, name)
			changed = true
		case content != "" && (!exists || string(old) != content):
			err = safefs.WriteFile(root, name, strings.NewReader(content), int64(len(content)), time.Time{}, 0o644)
			changed = true
		}
		root.Close()
		if err != nil {
			return false, err
		}
	}
	return changed, nil
}
